version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: pmsdb-dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  apache:
    image: httpd:2.4
    container_name: apache_server
    ports:
      - "52878:80"
      - "52879:8080"
    volumes:
      - ./my_apache_conf:/usr/local/apache2/conf
      - ./my_apache_html:/usr/local/apache2/htdocs

volumes:
  db_data:
